SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS algorithm(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ALGORITHM_NAME_ID VARCHAR(250) UNIQUE NOT NULL,
	ALGORITHM_NAME VARCHAR(250) NOT NULL,
	ALGORITHM_TYPE VARCHAR(250) NOT NULL,
	FILE_NAME VARCHAR(250) NOT NULL,
	FILE_TYPE VARCHAR(250) NOT NULL,
	FILE_PATH VARCHAR(250) NOT NULL,
	CONSTRAINT algorithm_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS dataset(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DATASET_NAME_ID VARCHAR(250) UNIQUE NOT NULL,
	DATASET_DISPLAY_NAME VARCHAR(250) NOT NULL,
	FILE_NAME VARCHAR(250) NOT NULL,
	FILE_PATH VARCHAR(250) NOT NULL,
	DATA_TYPE VARCHAR(250) NOT NULL,
	CONSTRAINT dataset_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS algorithm_dataset_mapping(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DATASET_ID BIGINT NOT NULL,
	ALGORITHM_ID BIGINT NOT NULL,
	CONSTRAINT algorithm_dataset_mapping_pk PRIMARY KEY (ID),
	CONSTRAINT dataset_fk FOREIGN KEY (DATASET_ID) REFERENCES dataset(ID),
	CONSTRAINT algorithm_fk FOREIGN KEY (ALGORITHM_ID) REFERENCES algorithm(ID)
);

SET FOREIGN_KEY_CHECKS = 1;