package com.project.algocomparator.models.enums;

public class DataSetType {
	public static final String RANDOM_UNIQUE_POSITIVE_INT = "RANDOM_UNIQUE_POSITIVE_INT";
	public static final String RANDOM_UNIQUE_NEGATIVE_INT = "RANDOM_UNIQUE_NEGATIVE_INT";
	public static final String RANDOM_UNIQUE_MIX_INT = "RANDOM_UNIQUE_MIX_INT";
	public static final String RANDOM_UNIQUE_FLOAT = "RANDOM_UNIQUE_FLOAT";
	public static final String RANDOM_REPEATIVE_POSITIVE_INT = "RANDOM_REPEATIVE_POSITIVE_INT";
	public static final String RANDOM_REPEATIVE_NEGATIVE_INT = "RANDOM_REPEATIVE_NEGATIVE_INT";
	public static final String RANDOM_REPEATIVE_MIX_INT = "RANDOM_REPEATIVE_MIX_INT";
	public static final String RANDOM_REPEATIVE_FLOAT = "RANDOM_REPEATIVE_FLOAT";
	public static final String SORTED_UNIQUE_POSITIVE_INT = "SORTED_UNIQUE_POSITIVE_INT";
	public static final String SORTED_UNIQUE_MIX_INT = "SORTED_UNIQUE_MIX_INT";
	public static final String SORTED_UNIQUE_NEGATIVE_INT = "SORTED_UNIQUE_NEGATIVE_INT";
	public static final String SORTED_UNIQUE_FLOAT = "SORTED_UNIQUE_FLOAT";
	public static final String SORTED_REPEATIVE_POSITIVE_INT = "SORTED_REPEATIVE_POSITIVE_INT";
	public static final String SORTED_REPEATIVE_NEGATIVE_INT = "SORTED_REPEATIVE_NEGATIVE_INT";
	public static final String SORTED_REPEATIVE_MIX_INT = "SORTED_REPEATIVE_MIX_INT";
	public static final String SORTED_REPEATIVE_FLOAT = "SORTED_REPEATIVE_FLOAT";
	public static final String UNRELATED_KNAPSACK_PROBLEM = "UNRELATED_KNAPSACK_PROBLEM";
	public static final String WEAKLY_CORELATED_KNAPSACK_PROBLEM = "WEAKLY_CORELATED_KNAPSACK_PROBLEM";
	public static final String STRONGLY_CORELATED_KNAPSACK_PROBLEM = "STRONGLY_CORELATED_KNAPSACK_PROBLEM";
}
